pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
    - ./node_modules
    volumes:
    - /tmp/cache:/cache
  build:
    image: node:9-alpine
    commands:
    - npm install
    - npm run build
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
    - ./node_modules
    volumes:
    - /tmp/cache:/cache
  build-notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: Drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job. (CommitID: {{build.commit}})
      {{else}}
        build {{build.number}} failed. Fix me please. (CommitID: {{build.commit}})
      {{/success}}
      URL: https://drone.syuchan.site/{{repo.owner}}/{{repo.name}}/{{build.number}}
  scp:
    image: appleboy/drone-scp
    host: 192.168.1.251
    username: drone
    password: drone
    source:
    - ./*
    target: /Server/School/Drone/backend
    when:
      status: [ success ]
  deploy-notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: Drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Deploy Complete!
      {{else}}
        deploy failed.
      {{/success}}

